name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout toolchain
      uses: actions/checkout@v2

    - name: Install Ninja
      run: choco install ninja --confirm
      shell: pwsh

    - name: Clone ngage-toolchain
      run: git clone https://github.com/ngagesdk/ngage-toolchain.git

    - name: Set up NGAGESDK environment variable
      run: |
        $ngagesdk = "${{ github.workspace }}/ngage-toolchain"
        $ngagesdk = $ngagesdk -replace '\\', '/'
        echo "NGAGESDK=$ngagesdk" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Add runtime paths to PATH
      run: |
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/gcc/bin" >> $env:GITHUB_PATH
        echo "${{ env.NGAGESDK }}/sdk/sdk/6.1/Shared/EPOC32/ngagesdk/bin" >> $env:GITHUB_PATH
      shell: pwsh

    - name: Verify directory structure
      run: |
        echo "NGAGESDK: ${{ env.NGAGESDK }}"
        ls ${{ env.NGAGESDK }}
        ls ${{ env.NGAGESDK }}/setup
      shell: pwsh

    - name: Fetch SDK
      run: cmake -G "Ninja" -S ${{ env.NGAGESDK }}/setup -B ${{ env.NGAGESDK }}/projects/Pico-8/out/build/N-Gage
      shell: pwsh

    - name: Remove existing Pico-8 directory
      run: Remove-Item -Recurse -Force ${{ env.NGAGESDK }}/projects/Pico-8
      shell: pwsh

    - name: Clone Pico-8
      run: git clone https://github.com/ngagesdk/Pico-8.git ${{ env.NGAGESDK }}/projects/Pico-8
      shell: pwsh

    - name: Build Pico-8
      run: |
        cmake -G "Ninja" -S ${{ env.NGAGESDK }}/projects/Pico-8 -B ${{ env.NGAGESDK }}/projects/Pico-8/out/build/N-Gage -DCMAKE_TOOLCHAIN_FILE=${{ env.NGAGESDK }}/cmake/ngage-toolchain.cmake
        cmake --build ${{ env.NGAGESDK }}/projects/Pico-8/out/build/N-Gage
      shell: pwsh

    - name: Archive Pico-8.sis
      uses: actions/upload-artifact@v4
      with:
        name: Pico-8.sis
        path: ${{ env.NGAGESDK }}/projects/Pico-8/out/build/N-Gage/Pico-8.sis

    - name: Build Test runner
      run: |
        cmake -G "Ninja" -S ${{ env.NGAGESDK }}/projects/Pico-8/tests -B ${{ env.NGAGESDK }}/projects/Pico-8/tests
        cmake --build ${{ env.NGAGESDK }}/projects/Pico-8/tests
      shell: pwsh

    - name: Verify Test Executable and SDL3.dll
      run: |
        ls ${{ env.NGAGESDK }}/projects/Pico-8/tests
      shell: pwsh

    - name: Run Tests
      run: |
        $exePath = "${{ env.NGAGESDK }}/projects/Pico-8/tests/tests.exe"
        if (Test-Path $exePath) {
          & $exePath
        } else {
          Write-Error "Test application not found!"
          exit 1
        }
      shell: pwsh
