name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x86

      - name: Build
        run: |
          cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Zip export directory
        run: Compress-Archive -Path export -DestinationPath Pico-8-Windows-x86.zip
        shell: pwsh

      - name: Archive Pico-8.zip
        uses: actions/upload-artifact@v4
        with:
          name: Pico-8-Windows-x86.zip
          path: Pico-8-Windows-x86.zip
